[
  {
    "id": "oe_bildungskonto-chunk-1",
    "text": "VORAUSSETZUNGEN\nHauptwohnsitz in Oberösterreich, Mindestalter 18 Jahre, anerkannter Bildungsträger erforderlich.",
    "normalizedText": "voraussetzungen\nhauptwohnsitz in oberoesterreich, mindestalter 18 jahre, anerkannter bildungstraeger erforderlich.",
    "programId": "oe_bildungskonto",
    "programName": "Bildungskonto OÖ",
    "page": 13,
    "section": "voraussetzungen",
    "stand": "09/2025",
    "status": "aktiv",
    "startChar": 0,
    "endChar": 112
  },
  {
    "id": "ams_qbn-chunk-1",
    "text": "ÜBERBLICK\nQBN – Qualifizierungsförderung für Beschäftigte unterstützt die berufliche Weiterbildung durch gezielte Fördermaßnahmen.",
    "normalizedText": "ueberblick\nqbn – qualifizierungsfoerderung fuer beschaeftigte unterstuetzt die berufliche weiterbildung durch gezielte foerdermassnahmen.",
    "programId": "ams_qbn",
    "programName": "QBN – Qualifizierungsförderung für Beschäftigte",
    "page": 8,
    "section": "überblick",
    "stand": "10/2025",
    "status": "aktiv",
    "startChar": 0,
    "endChar": 130
  },
  {
    "id": "ams_qbn-chunk-1",
    "text": "VORAUSSETZUNGEN\nHauptwohnsitz in Oberösterreich, Mindestalter 18 Jahre, anerkannter Bildungsträger erforderlich.",
    "normalizedText": "voraussetzungen\nhauptwohnsitz in oberoesterreich, mindestalter 18 jahre, anerkannter bildungstraeger erforderlich.",
    "programId": "ams_qbn",
    "programName": "QBN – Qualifizierungsförderung für Beschäftigte",
    "page": 9,
    "section": "voraussetzungen",
    "stand": "10/2025",
    "status": "aktiv",
    "startChar": 0,
    "endChar": 112
  },
  {
    "id": "innovative_skills_ooe-chunk-1",
    "text": "ÜBERBLICK\nInnovative Skills - Land OÖ unterstützt die berufliche Weiterbildung durch gezielte Fördermaßnahmen.",
    "normalizedText": "ueberblick\ninnovative skills - land ooe unterstuetzt die berufliche weiterbildung durch gezielte foerdermassnahmen.",
    "programId": "innovative_skills_ooe",
    "programName": "Innovative Skills - Land OÖ",
    "page": 24,
    "section": "überblick",
    "stand": "11/2025",
    "status": "endet_am",
    "startChar": 0,
    "endChar": 110
  },
  {
    "id": "innovative_skills_ooe-chunk-1",
    "text": "VORAUSSETZUNGEN\nHauptwohnsitz in Oberösterreich, Mindestalter 18 Jahre, anerkannter Bildungsträger erforderlich.",
    "normalizedText": "voraussetzungen\nhauptwohnsitz in oberoesterreich, mindestalter 18 jahre, anerkannter bildungstraeger erforderlich.",
    "programId": "innovative_skills_ooe",
    "programName": "Innovative Skills - Land OÖ",
    "page": 25,
    "section": "voraussetzungen",
    "stand": "11/2025",
    "status": "endet_am",
    "startChar": 0,
    "endChar": 112
  },
  {
    "id": "qualifizierungsverbund_digi_nachhaltigkeit-chunk-1",
    "text": "ÜBERBLICK\nQualifizierungsverbund - Digitale Kompetenz & Nachhaltigkeit unterstützt die berufliche Weiterbildung durch gezielte Fördermaßnahmen.",
    "normalizedText": "ueberblick\nqualifizierungsverbund - digitale kompetenz & nachhaltigkeit unterstuetzt die berufliche weiterbildung durch gezielte foerdermassnahmen.",
    "programId": "qualifizierungsverbund_digi_nachhaltigkeit",
    "programName": "Qualifizierungsverbund - Digitale Kompetenz & Nachhaltigkeit",
    "page": 18,
    "section": "überblick",
    "stand": "09/2025",
    "status": "aktiv",
    "startChar": 0,
    "endChar": 143
  },
  {
    "id": "qualifizierungsverbund_digi_nachhaltigkeit-chunk-1",
    "text": "VORAUSSETZUNGEN\nHauptwohnsitz in Oberösterreich, Mindestalter 18 Jahre, anerkannter Bildungsträger erforderlich.",
    "normalizedText": "voraussetzungen\nhauptwohnsitz in oberoesterreich, mindestalter 18 jahre, anerkannter bildungstraeger erforderlich.",
    "programId": "qualifizierungsverbund_digi_nachhaltigkeit",
    "programName": "Qualifizierungsverbund - Digitale Kompetenz & Nachhaltigkeit",
    "page": 19,
    "section": "voraussetzungen",
    "stand": "09/2025",
    "status": "aktiv",
    "startChar": 0,
    "endChar": 112
  },
  {
    "id": "aqua-chunk-1",
    "text": "ÜBERBLICK\nAQUA - Arbeitsplatznahe Qualifizierung unterstützt die berufliche Weiterbildung durch gezielte Fördermaßnahmen.",
    "normalizedText": "ueberblick\naqua - arbeitsplatznahe qualifizierung unterstuetzt die berufliche weiterbildung durch gezielte foerdermassnahmen.",
    "programId": "aqua",
    "programName": "AQUA - Arbeitsplatznahe Qualifizierung",
    "page": 32,
    "section": "überblick",
    "stand": "10/2025",
    "status": "aktiv",
    "startChar": 0,
    "endChar": 121
  },
  {
    "id": "aqua-chunk-1",
    "text": "VORAUSSETZUNGEN\nHauptwohnsitz in Oberösterreich, Mindestalter 18 Jahre, anerkannter Bildungsträger erforderlich.",
    "normalizedText": "voraussetzungen\nhauptwohnsitz in oberoesterreich, mindestalter 18 jahre, anerkannter bildungstraeger erforderlich.",
    "programId": "aqua",
    "programName": "AQUA - Arbeitsplatznahe Qualifizierung",
    "page": 33,
    "section": "voraussetzungen",
    "stand": "10/2025",
    "status": "aktiv",
    "startChar": 0,
    "endChar": 112
  },
  {
    "id": "fit-chunk-1",
    "text": "ÜBERBLICK\nFiT - Frauen in Handwerk und Technik unterstützt die berufliche Weiterbildung durch gezielte Fördermaßnahmen.",
    "normalizedText": "ueberblick\nfit - frauen in handwerk und technik unterstuetzt die berufliche weiterbildung durch gezielte foerdermassnahmen.",
    "programId": "fit",
    "programName": "FiT - Frauen in Handwerk und Technik",
    "page": 45,
    "section": "überblick",
    "stand": "11/2025",
    "status": "aktiv",
    "startChar": 0,
    "endChar": 119
  },
  {
    "id": "fit-chunk-1",
    "text": "VORAUSSETZUNGEN\nHauptwohnsitz in Oberösterreich, Mindestalter 18 Jahre, anerkannter Bildungsträger erforderlich.",
    "normalizedText": "voraussetzungen\nhauptwohnsitz in oberoesterreich, mindestalter 18 jahre, anerkannter bildungstraeger erforderlich.",
    "programId": "fit",
    "programName": "FiT - Frauen in Handwerk und Technik",
    "page": 46,
    "section": "voraussetzungen",
    "stand": "11/2025",
    "status": "aktiv",
    "startChar": 0,
    "endChar": 112
  }
]